language: java
script: "./buildViaTravis.sh"
deploy:
  provider: releases
  api_key:
    secure: Wm3q47PURcTs4B3jZO2dNuWI1nJDb0QQSYIbYO1pozByXmaSETUf9ksj8sT7dGfv5l5Iee5Irm/1wLEneueRr0YncgfwRnSNMMnOR+wUlIIRpJD0F8o6fMC5TvT31sMcOrSsaP4CnghStygqZw8N3A9sBWjBIpqx9R45P9wcVoNzF2AErxblxnSkLgMjecugW5oAIpPlZsbl/oa26HVBLFLIhT4Zz2GhnmQSeXYXEbUyoXNsJRZeyWDUBK+H1c4rJ6sbCCvM+Rtlz9b/1oSfSVepj9hpqVMq5Q46RQPS3UGAWLUjZ0Je/7Q6v6ThIXOU2+nAYJ44HWMSkiHtdHdzW9EJaDdIimHs5YyYQOqkNcTHGhhxDzUmpq7pD8YzhPLuQFD0A7JD9YyFMWaxhjJLHoxSpozquQiuvagX69WrVTbLpJC3pOHnDmcKgmra9CCAX5jNrlpRtiGJ1bSeaVll2CAuTLc1zVv0y7I53k0nuWCXiY4AT6wTX1iYF8wbyjUhxZ90yt82R5MJ7o9erXjldZw4ThatDiN9OHua/sK6jS7pCIkQHmHpHNWCC/nGzQ/dMEeCd3ZnXblV/4Xr29YWsxjbQJ3ZZ8fVbv/MZXHvgHxLVU4+FPVgU2yt4Vdp6DyHRh0nj99IJ6sy3lS1lW1DBC59qmYL6FccVa4X6SDWFY4=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  edge: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-google-cloud-compute-plugin

